### ISSUE TITLE
docs: typo glitch in installation.rst

### ISSUE THREAD

**Issue by cmulay** [nucleic/cppy#11]
The installation.rst file is well written, but on the published doc there is a typo glitch:

In ``docs/source/installation.rst``  on line ``10`` the typo is correct but on published version it isn't.

Attached Screenshot:
![glitch](https://user-images.githubusercontent.com/38172685/118377313-1c7f1f80-b5ea-11eb-901b-d6748762cf02.png)

Fix:
Removing and adding GitHub (Rewriting in individual commits)

**Comment by MatthieuDartiailh** [comment]
Fixed the configuration of read the docs had not been updated after going from `master` to `main`. Thanks
