### ISSUE TITLE
Release version compatible with setuptools pyproject validation (>=60.2.0)

### ISSUE THREAD

**Issue by mweinelt** [nucleic/cppy#20]
I noticed you already moved completely to pyproject.toml, but with version 1.2.0 we're still seeing validation issues with `setuptools==61.2.0`.

>     version should be statically defined in the ``version`` field

Please release a new version that passes `validate-pyproject`, I think the `main` branch does.

**Comment by MatthieuDartiailh** [comment]
1.2.1 is now live
