### ISSUE TITLE
v1.2.1: Missing package name and header files

### ISSUE THREAD

**Issue by algent-al** [nucleic/cppy#21]
Hello!

I am updating cppy for Solus, and I noticed that version 1.2.1 doesn't seem right.
Below you can see the changes between the last v.1.2.0 and 1.2.1.

```
         <Files>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy-1.2.0-py3.9.egg-info/PKG-INFO</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy-1.2.0-py3.9.egg-info/SOURCES.txt</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy-1.2.0-py3.9.egg-info/dependency_links.txt</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy-1.2.0-py3.9.egg-info/top_level.txt</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/__init__.py</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/__pycache__/__init__.cpython-39.pyc</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/__pycache__/version.cpython-39.pyc</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/include/cppy/cppy.h</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/include/cppy/defines.h</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/include/cppy/errors.h</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/include/cppy/ptr.h</Path>
-            <Path fileType="library">/usr/lib/python3.9/site-packages/cppy/version.py</Path>
+            <Path fileType="library">/usr/lib/python3.9/site-packages/UNKNOWN-1.2.1-py3.9.egg-info/PKG-INFO</Path>
+            <Path fileType="library">/usr/lib/python3.9/site-packages/UNKNOWN-1.2.1-py3.9.egg-info/SOURCES.txt</Path>
+            <Path fileType="library">/usr/lib/python3.9/site-packages/UNKNOWN-1.2.1-py3.9.egg-info/dependency_links.txt</Path>
+            <Path fileType="library">/usr/lib/python3.9/site-packages/UNKNOWN-1.2.1-py3.9.egg-info/top_level.txt</Path>
         </Files>
```

`cppy` isn't recognized as the package name and it is reported as `UNKNOWN`.
Also all header files are missing.

As source I used tarball from PyPI: `https://files.pythonhosted.org/packages/source/c/cppy/cppy-1.2.1.tar.gz`

Looks like same issue is with Arch Linux too.
https://archlinux.org/packages/community/any/python-cppy/

**Comment by phmccarty** [comment]
Perhaps this is related to the new setuptools minimum version (61.2) declared in the pyproject.toml? See https://github.com/nucleic/cppy/commit/d20920b129d123211531c9f63ea717da433a67ea

Arch Linux is currently shipping setuptools 59.5.0...

**Comment by MatthieuDartiailh** [comment]
I agree with the diagnostic here. Is there anything you would need from my end as maintainer ?

**Comment by bryteise** [comment]
@MatthieuDartiailh I think project maintainers are kind of in a tough spot. You could keep the old setup.py around and let folks on older setuptools still use that because the distros are struggling to adopt the newer setuptools as it won't work with projects not using the new pyproject build.

**Comment by MatthieuDartiailh** [comment]
I am extremely hesitant to roll back things since setuptools rightfully complains if the same information is made available both in the pyproject.toml and setup.py. Going down this road I would never update in case somebody is still using an old distro and not installing through pip.

**Comment by bryteise** [comment]
Oh I don't disagree, you'd likely need to do some rather questionable version tests in setup.py to make it somewhat work. I just think that's probably the only way to support both.

**Comment by algent-al** [comment]
Issue resolved by updating `setuptools`.
